language: node_js

sudo: false

compiler:
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - npm install
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

node_js:
  - "0.12"
  - "0.10"
  - "iojs"
  - "4.1"
